-- Contact messages
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  message text not null,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

create policy "anyone can submit contact" on public.contact_messages
  for insert to anon, authenticated with check (true);

create policy "staff read contact" on public.contact_messages
  for select using (public.is_staff(auth.uid()));

create policy "staff write contact" on public.contact_messages
  for all using (public.is_staff(auth.uid())) with check (public.is_staff(auth.uid()));

-- Newsletter subscribers
create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text,
  created_at timestamptz not null default now()
);

alter table public.newsletter_subscribers enable row level security;

create policy "anyone can subscribe" on public.newsletter_subscribers
  for insert to anon, authenticated with check (true);

create policy "staff read subscribers" on public.newsletter_subscribers
  for select using (public.is_staff(auth.uid()));

create policy "staff write subscribers" on public.newsletter_subscribers
  for all using (public.is_staff(auth.uid())) with check (public.is_staff(auth.uid()));
